"""Add OTP fields

Revision ID: 39a24832d877
Revises: 444fb2778100
Create Date: 2025-06-13 15:19:22.039179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39a24832d877'
down_revision: Union[str, None] = '444fb2778100'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('reset_otp', sa.String(), nullable=True))
    op.add_column('users', sa.Column('reset_otp_expires', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('otp_attempts', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('last_otp_request', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_otp_request')
    op.drop_column('users', 'otp_attempts')
    op.drop_column('users', 'reset_otp_expires')
    op.drop_column('users', 'reset_otp')
    # ### end Alembic commands ###
